export type FormulaTemplateGroup = { id: string; labelKey: string; items: string[] };

export const FORMULA_TEMPLATES: FormulaTemplateGroup[] = [
  {
    id: "basic",
    labelKey: "viewer.formula.groups.basic",
    items: [
      String.raw`\frac{a}{b}`,
      String.raw`x^{n}`,
      String.raw`x_{i}`,
      String.raw`\sqrt{x}`,
      String.raw`\sqrt[n]{x}`,
      String.raw`\left| x \right|`,
      String.raw`\pm`,
      String.raw`\times`,
      "÷",
      String.raw`\neq`,
      String.raw`\leq`,
      String.raw`\geq`,
      String.raw`\approx`,
      String.raw`\infty`,
      String.raw`\%`,
      String.raw`\cdot`,
    ],
  },
  {
    id: "calculus",
    labelKey: "viewer.formula.groups.calculus",
    items: [
      String.raw`\int f(x)\,dx`,
      String.raw`\int_{a}^{b} f(x)\,dx`,
      String.raw`\iint_{D} f\,dA`,
      String.raw`\oint_{C} \vec{F}\cdot d\vec{r}`,
      String.raw`\frac{d}{dx} f(x)`,
      String.raw`f'(x)`,
      String.raw`\frac{\partial f}{\partial x}`,
      String.raw`\lim_{x \to \infty} f(x)`,
      String.raw`\sum_{i=1}^{n} a_i`,
      String.raw`\prod_{i=1}^{n} a_i`,
      String.raw`\nabla f`,
      String.raw`e^{i\pi} + 1 = 0`,
    ],
  },
  {
    id: "algebra",
    labelKey: "viewer.formula.groups.algebra",
    items: [
      String.raw`x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`,
      String.raw`\binom{n}{k}`,
      String.raw`\log_{a} x`,
      String.raw`\ln x`,
      String.raw`(a + b)^2 = a^2 + 2ab + b^2`,
      String.raw`a^2 - b^2 = (a - b)(a + b)`,
      String.raw`a^m \cdot a^n = a^{m+n}`,
      String.raw`\log_a (xy) = \log_a x + \log_a y`,
      String.raw`\vec{v}`,
      String.raw`\lfloor x \rfloor \quad \lceil x \rceil`,
      String.raw`x \equiv a \pmod{n}`,
    ],
  },
  {
    id: "matrices",
    labelKey: "viewer.formula.groups.matrices",
    items: [
      String.raw`\begin{pmatrix} a & b \\ c & d \end{pmatrix}`,
      String.raw`\begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}`,
      String.raw`\begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc`,
      String.raw`I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}`,
      String.raw`A = \begin{bmatrix} a_{11} & \cdots & a_{1n} \\ \vdots & \ddots & \vdots \\ a_{m1} & \cdots & a_{mn} \end{bmatrix}`,
      String.raw`\left[\begin{array}{cc|c} 1 & 2 & 3 \\ 4 & 5 & 6 \end{array}\right]`,
      String.raw`\begin{pmatrix} x \\ y \\ z \end{pmatrix}`,
      String.raw`A^{T} \quad A^{-1} \quad \det(A)`,
      String.raw`A^{-1} = \frac{1}{ad - bc}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}`,
      String.raw`\begin{cases} 2x + y = 5 \\ x - y = 1 \end{cases}`,
      String.raw`\begin{aligned} a_1x + b_1y &= c_1 \\ a_2x + b_2y &= c_2 \end{aligned}`,
      String.raw`f(x) = \begin{cases} x & x \geq 0 \\ -x & x < 0 \end{cases}`,
    ],
  },
  {
    id: "logic",
    labelKey: "viewer.formula.groups.logic",
    items: [
      String.raw`\in \quad \notin`,
      String.raw`A \subset B \quad A \subseteq B`,
      String.raw`A \cup B \quad A \cap B`,
      String.raw`A \setminus B \quad A^{c}`,
      String.raw`\emptyset`,
      String.raw`\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R} \subset \mathbb{C}`,
      String.raw`\{ x \in \mathbb{R} \mid x > 0 \}`,
      String.raw`[a, b) \quad (a, \infty)`,
      String.raw`s(A \cup B) = s(A) + s(B) - s(A \cap B)`,
      String.raw`\forall x \; \exists y`,
      String.raw`p \land q \quad p \lor q \quad \lnot p`,
      String.raw`p \Rightarrow q \quad p \Leftrightarrow q`,
      String.raw`f\colon A \to B`,
      String.raw`(g \circ f)(x)`,
    ],
  },
  {
    id: "statistics",
    labelKey: "viewer.formula.groups.statistics",
    items: [
      String.raw`\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i`,
      String.raw`\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n} (x_i - \mu)^2}`,
      String.raw`s^2 = \frac{1}{n-1}\sum_{i=1}^{n} (x_i - \bar{x})^2`,
      String.raw`P(A) = \frac{s(A)}{s(E)}`,
      String.raw`P(A \mid B) = \frac{P(A \cap B)}{P(B)}`,
      String.raw`P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B)}`,
      String.raw`P(A \cup B) = P(A) + P(B) - P(A \cap B)`,
      String.raw`C(n, r) = \frac{n!}{r!\,(n-r)!}`,
      String.raw`P(n, r) = \frac{n!}{(n-r)!}`,
      String.raw`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}`,
      String.raw`E[X] = \sum_{i} x_i\, p_i`,
      String.raw`z = \frac{x - \mu}{\sigma}`,
      String.raw`f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}`,
    ],
  },
  {
    id: "layout",
    labelKey: "viewer.formula.groups.layout",
    items: [
      String.raw`\begin{aligned} f(x) &= (x+1)^2 \\ &= x^2 + 2x + 1 \end{aligned}`,
      String.raw`\begin{gathered} a + b = c \\ d - e = f \end{gathered}`,
      String.raw`a + b = c \tag{1}`,
      String.raw`\boxed{E = mc^2}`,
      String.raw`\underbrace{a + \cdots + a}_{n}`,
      String.raw`\overbrace{x + y}^{k}`,
      String.raw`\text{…} \quad x^2`,
      String.raw`\cancel{x}`,
      String.raw`\enclose{circle}{1}`,
      String.raw`\color{red}{x}`,
      String.raw`A \xrightarrow[b]{a} B`,
      String.raw`\stackrel{?}{=}`,
    ],
  },
  {
    id: "geometry",
    labelKey: "viewer.formula.groups.geometry",
    items: [
      String.raw`a^2 + b^2 = c^2`,
      String.raw`A = \pi r^2`,
      String.raw`C = 2\pi r`,
      String.raw`V = \frac{4}{3}\pi r^3`,
      String.raw`\sin^2\theta + \cos^2\theta = 1`,
      String.raw`\tan\theta = \frac{\sin\theta}{\cos\theta}`,
      String.raw`\angle ABC = 90^\circ`,
      String.raw`\triangle ABC \cong \triangle DEF`,
      String.raw`AB \parallel CD`,
      String.raw`AB \perp CD`,
      String.raw`\overline{AB}`,
      String.raw`\overrightarrow{AB}`,
    ],
  },
  {
    id: "greek",
    labelKey: "viewer.formula.groups.greek",
    items: [
      String.raw`\alpha`,
      String.raw`\beta`,
      String.raw`\gamma`,
      String.raw`\delta`,
      String.raw`\varepsilon`,
      String.raw`\theta`,
      String.raw`\lambda`,
      String.raw`\mu`,
      String.raw`\pi`,
      String.raw`\rho`,
      String.raw`\sigma`,
      String.raw`\tau`,
      String.raw`\varphi`,
      String.raw`\omega`,
      String.raw`\Delta`,
      String.raw`\Sigma`,
      String.raw`\Phi`,
      String.raw`\Omega`,
    ],
  },
  {
    id: "physics",
    labelKey: "viewer.formula.groups.physics",
    items: [
      String.raw`\vec{F} = m\vec{a}`,
      String.raw`E = mc^2`,
      String.raw`E_k = \frac{1}{2}mv^2`,
      String.raw`E_p = mgh`,
      String.raw`F = G\frac{m_1 m_2}{r^2}`,
      String.raw`F = k\frac{q_1 q_2}{r^2}`,
      String.raw`V = IR`,
      String.raw`P = VI`,
      String.raw`v = \frac{\Delta x}{\Delta t}`,
      String.raw`x = x_0 + v_0 t + \frac{1}{2}at^2`,
      String.raw`\vec{p} = m\vec{v}`,
      String.raw`v = \lambda f`,
      String.raw`E = h\nu`,
      String.raw`PV = nRT`,
      String.raw`i\hbar\frac{\partial}{\partial t}\Psi = \hat{H}\Psi`,
      String.raw`\nabla \cdot \vec{E} = \frac{\rho}{\varepsilon_0}`,
    ],
  },
  {
    id: "chemistry",
    labelKey: "viewer.formula.groups.chemistry",
    items: [
      String.raw`\ce{H2O}`,
      String.raw`\ce{2H2 + O2 -> 2H2O}`,
      String.raw`\ce{CH4 + 2O2 -> CO2 + 2H2O}`,
      String.raw`\ce{N2 + 3H2 <=> 2NH3}`,
      String.raw`\ce{SO4^2-}`,
      String.raw`\ce{NaCl_{(aq)}}`,
      String.raw`\ce{CaCO3 ->[\Delta] CaO + CO2 ^}`,
      String.raw`\ce{^{14}_{6}C}`,
    ],
  },
];

export function insertAt(text: string, insertion: string, start: number, end: number): { text: string; caret: number } {
  const from = Math.max(0, Math.min(start, text.length));
  const to = Math.max(from, Math.min(end, text.length));
  const before = text.slice(0, from);
  const spacer = /[A-Za-z]$/.test(before) && !insertion.startsWith("\\") ? " " : "";
  const inserted = `${spacer}${insertion}`;
  return { text: `${before}${inserted}${text.slice(to)}`, caret: from + inserted.length };
}
