MODULE_OPERATIONS: dict[str, tuple[str, ...]] = {
    "a11y": ("a11y.check",),
    "a11y_fix": ("a11y.fix",),
    "a11y_preview": ("a11y.figurePreview",),
    "analyze": (
        "pages.analyze",
        "pages.duplicates",
        "pages.impose",
    ),
    "attachments": (
        "attachments.add",
        "attachments.extract",
        "attachments.list",
        "attachments.remove",
    ),
    "bookmarks": (
        "bookmarks.add",
        "bookmarks.generate",
        "bookmarks.get",
        "bookmarks.set",
        "bookmarks.suggest",
    ),
    "bookmarks_transfer": (
        "bookmarks.export",
        "bookmarks.import",
        "bookmarks.parse",
    ),
    "clipboard": ("create.clipboard",),
    "codeblocks": ("textedit.code_blocks",),
    "codes": (
        "codes.add_qr",
        "codes.export_csv",
        "codes.read",
    ),
    "comments": (
        "comments.delete",
        "comments.export",
        "comments.list",
        "comments.reply",
        "comments.set_resolved",
        "comments.set_state",
    ),
    "comments_xfdf": ("comments.import",),
    "compare": (
        "compare.pageImages",
        "compare.run",
    ),
    "compress": ("compress.run",),
    "compress_preview": ("compress.preview",),
    "convert": (
        "convert.extract_images",
        "convert.to_docx",
        "convert.tools",
    ),
    "convert_images": (
        "convert.images_to_pdf",
        "convert.to_images",
    ),
    "convert_slides": ("convert.to_pptx",),
    "convert_tables": ("convert.to_xlsx",),
    "convert_text": (
        "convert.to_html",
        "convert.to_markdown",
        "convert.to_text",
    ),
    "convert_to_pdf": (
        "convert.file_to_pdf",
        "convert.svg_to_pdf",
    ),
    "cover": ("pages.cover",),
    "create": ("create.document",),
    "create_book": ("create.book",),
    "create_bulk": ("create.bulk",),
    "create_paper": ("create.paper",),
    "edit": (
        "security.redact",
        "security.redact_preview",
        "security.scan_presets",
    ),
    "editor": (
        "editor.apply",
        "editor.image_preview",
    ),
    "editor_blocks": (
        "editor.blocks",
        "editor.font",
        "editor.font_plan",
    ),
    "editor_chart": ("editor.chart_preview",),
    "editor_flowchart": ("editor.flowchart_preview",),
    "editor_question": ("editor.question_preview",),
    "editor_table": ("editor.table_preview",),
    "epub": ("convert.to_epub",),
    "fallback_fonts": (
        "system.fallback_fonts",
        "system.fallback_fonts_download",
        "system.fallback_fonts_remove",
    ),
    "flatten": ("security.flatten",),
    "folders": (
        "files.list_pdfs",
        "files.move_to_folder",
    ),
    "font_library": (
        "fonts.library",
        "fonts.library_download",
        "fonts.library_remove",
    ),
    "fonts": (
        "editor.system_fonts",
        "fonts.add",
        "fonts.catalogue",
        "fonts.file",
        "fonts.remove",
    ),
    "forms": (
        "forms.fields",
        "forms.fill",
        "forms.reset",
    ),
    "forms_batch": (
        "forms.data_preview",
        "forms.merge",
    ),
    "forms_data": (
        "forms.export_data",
        "forms.import_data",
    ),
    "forms_detect": ("forms.detect",),
    "forms_export": ("forms.export",),
    "furniture": ("pages.remove_header_footer",),
    "header_footer": ("pages.header_footer",),
    "images": (
        "images.at",
        "images.save",
    ),
    "info": (
        "info.get",
        "info.page_labels",
        "info.text",
        "info.thumbnail",
    ),
    "layers": ("layers.list",),
    "letterhead": ("pages.letterhead",),
    "links": (
        "links.add",
        "links.autolink",
        "links.list",
        "links.remove",
    ),
    "merge_split": (
        "pages.merge",
        "pages.split",
    ),
    "metadata": ("info.set_metadata",),
    "ocr": (
        "ocr.area",
        "ocr.run",
        "ocr.searchable",
        "ocr.text",
    ),
    "office": (
        "system.office_install",
        "system.office_remove",
        "system.office_status",
    ),
    "omr": (
        "omr.export",
        "omr.read",
        "omr.review",
        "omr.sheet",
    ),
    "page_geometry": (
        "pages.crop",
        "pages.resize",
    ),
    "page_numbers": ("pages.number",),
    "page_tones": ("viewer.pageTones",),
    "pages": (
        "pages.assemble",
        "pages.assemble_parts",
        "pages.delete",
        "pages.edit",
        "pages.extract",
        "pages.find_text",
        "pages.insert_blank",
        "pages.insert_from",
        "pages.reverse",
        "pages.rotate",
    ),
    "password_breach": ("security.password_breach",),
    "pdfa": (
        "pdfa.check",
        "pdfa.convert",
    ),
    "pdfa_validate": (
        "pdfa.validate",
        "pdfa.validator",
    ),
    "photo": (
        "scan.from_photo",
        "scan.photo_detect",
    ),
    "poster": ("pages.poster",),
    "preflight": ("preflight.check",),
    "printing": (
        "print.printers",
        "print.run",
    ),
    "privacy": ("security.inspect",),
    "privacy_sanitize": ("security.sanitize",),
    "redaction_scrub": (
        "security.redacted_text",
        "security.scrub_hidden",
    ),
    "rename": (
        "rename.apply",
        "rename.preview",
        "rename.undo",
    ),
    "repair": ("repair.run",),
    "rotate": (
        "pages.auto_rotate",
        "pages.detect_rotation",
    ),
    "scan": (
        "scan.enhance",
        "scan.enhancePreview",
        "scan.separatorSheet",
        "scan.split",
        "scan.splitPreview",
    ),
    "scan_session": (
        "scanner.assemble",
        "scanner.discard",
    ),
    "scanner": (
        "scanner.acquire",
        "scanner.devices",
    ),
    "search": (
        "search.add_folder",
        "search.clear_all",
        "search.folders",
        "search.index",
        "search.query",
        "search.remove_folder",
        "search.stats",
    ),
    "security": (
        "security.decrypt",
        "security.encrypt",
    ),
    "security_certificate": (
        "security.decrypt_certificate",
        "security.encrypt_certificate",
    ),
    "security_watermark": (
        "security.watermark",
        "security.watermark_preview",
    ),
    "sign": (
        "sign.count",
        "sign.fields",
        "sign.run",
    ),
    "sign_certificate": (
        "sign.create_certificate",
        "sign.export_certificate",
    ),
    "sign_trust": (
        "sign.trust_add",
        "sign.trust_clear",
        "sign.trust_list",
        "sign.trust_preview",
        "sign.trust_remove",
    ),
    "sign_verify": ("sign.verify",),
    "signature": (
        "signature.clean",
        "signature.place",
    ),
    "space": ("compress.space",),
    "stamp": (
        "security.stamp",
        "security.stamp_preview",
    ),
    "studio": (
        "studio.image_info",
        "studio.import_svg",
        "studio.qr",
        "studio.render",
    ),
    "studio_document": (
        "studio.document_image",
        "studio.import_document",
        "studio.open_document",
        "studio.preview_document",
        "studio.preview_document_page",
        "studio.render_document",
        "studio.save_document",
    ),
    "studio_draft": (
        "studio.load_draft",
        "studio.save_draft",
    ),
    "studio_images": ("studio.save_image",),
    "studio_project": (
        "studio.design_of",
        "studio.open_project",
        "studio.save_project",
        "studio.thumbnail",
    ),
    "system": (
        "system.ping",
        "system.release",
    ),
    "tessdata": (
        "system.tessdata_download",
        "system.tessdata_languages",
        "system.tessdata_remove",
    ),
    "textedit": (
        "textedit.find_preview",
        "textedit.find_replace",
        "textedit.replace",
        "textedit.spans",
    ),
    "translate": (
        "translate.download",
        "translate.import",
        "translate.models",
        "translate.remove",
        "translate.text",
    ),
    "tts": (
        "tts.download",
        "tts.import",
        "tts.remove",
        "tts.synthesize",
        "tts.voices",
    ),
    "viewing": (
        "viewer.prepare",
        "viewer.restore",
    ),
    "watermark_detection": ("security.detect_watermark",),
    "watermark_removal": ("security.remove_watermark",),
    "web": ("convert.from_url",),
}

OPERATION_MODULES: dict[str, str] = {
    name: module for module, names in MODULE_OPERATIONS.items() for name in names
}
