HEADINGS: dict[str, tuple[str, ...]] = {
    "experience": (
        "experience",
        "work experience",
        "professional experience",
        "employment",
        "employment history",
        "work history",
        "career history",
        "relevant experience",
        "deneyim",
        "deneyimler",
        "iş deneyimi",
        "iş deneyimleri",
        "profesyonel deneyim",
        "iş tecrübesi",
        "tecrübe",
        "berufserfahrung",
        "erfahrung",
        "berufliche erfahrung",
        "berufspraxis",
        "expérience",
        "expériences",
        "expérience professionnelle",
        "expériences professionnelles",
        "experiencia",
        "experiencia laboral",
        "experiencia profesional",
        "esperienza",
        "esperienze",
        "esperienza professionale",
        "esperienze lavorative",
        "esperienza lavorativa",
        "experiência",
        "experiência profissional",
        "الخبرة",
        "الخبرات",
        "الخبرة العملية",
        "الخبرة المهنية",
    ),
    "education": (
        "education",
        "academic background",
        "educational background",
        "eğitim",
        "eğitim bilgileri",
        "öğrenim",
        "öğrenim bilgileri",
        "ausbildung",
        "bildung",
        "bildungsweg",
        "studium",
        "formation",
        "formations",
        "éducation",
        "études",
        "educación",
        "formación",
        "formación académica",
        "istruzione",
        "formazione",
        "educação",
        "formação",
        "formação acadêmica",
        "التعليم",
        "المؤهلات العلمية",
    ),
    "skills": (
        "skills",
        "top skills",
        "technical skills",
        "core skills",
        "key skills",
        "competencies",
        "core competencies",
        "expertise",
        "yetenekler",
        "beceriler",
        "yetkinlikler",
        "teknik beceriler",
        "uzmanlık alanları",
        "kenntnisse",
        "fähigkeiten",
        "fachkenntnisse",
        "kompetenzen",
        "compétences",
        "compétences techniques",
        "habilidades",
        "competencias",
        "aptitudes",
        "competenze",
        "competenze tecniche",
        "abilità",
        "competências",
        "المهارات",
    ),
    "languages": (
        "languages",
        "language skills",
        "diller",
        "yabancı diller",
        "yabancı dil",
        "sprachen",
        "sprachkenntnisse",
        "langues",
        "compétences linguistiques",
        "idiomas",
        "lenguas",
        "lingue",
        "conoscenze linguistiche",
        "línguas",
        "اللغات",
    ),
    "summary": (
        "summary",
        "professional summary",
        "profile",
        "professional profile",
        "about",
        "about me",
        "objective",
        "career objective",
        "özet",
        "profesyonel özet",
        "hakkımda",
        "profil",
        "kariyer hedefi",
        "kurzprofil",
        "über mich",
        "zusammenfassung",
        "résumé",
        "à propos",
        "à propos de moi",
        "resumen",
        "perfil",
        "sobre mí",
        "perfil profesional",
        "sommario",
        "profilo",
        "chi sono",
        "riepilogo",
        "resumo",
        "sobre mim",
        "perfil profissional",
        "نبذة",
        "نبذة عني",
        "الملخص",
    ),
    "certificates": (
        "certifications",
        "certificates",
        "certification",
        "licenses & certifications",
        "licenses and certifications",
        "licences & certifications",
        "sertifikalar",
        "sertifikalarım",
        "belgeler",
        "lisanslar ve sertifikalar",
        "zertifikate",
        "zertifizierungen",
        "certificats",
        "certificaciones",
        "certificados",
        "certificazioni",
        "certificati",
        "certificações",
        "الشهادات",
    ),
    "projects": (
        "projects",
        "personal projects",
        "selected projects",
        "key projects",
        "projeler",
        "projelerim",
        "projekte",
        "projets",
        "proyectos",
        "progetti",
        "projetos",
        "المشاريع",
    ),
    "references": (
        "references",
        "referanslar",
        "referenzen",
        "références",
        "referencias",
        "referenze",
        "referências",
        "المراجع",
        "المعرفين",
    ),
    "interests": (
        "interests",
        "hobbies",
        "hobbies and interests",
        "hobbies & interests",
        "ilgi alanları",
        "hobiler",
        "interessen",
        "hobbys",
        "centres d'intérêt",
        "loisirs",
        "intereses",
        "aficiones",
        "interessi",
        "hobby",
        "interesses",
        "الاهتمامات",
        "الهوايات",
    ),
    "contact": (
        "contact",
        "contacts",
        "contact information",
        "contact details",
        "iletişim",
        "iletişim bilgileri",
        "kontakt",
        "kontaktdaten",
        "coordonnées",
        "contacto",
        "datos de contacto",
        "contatti",
        "contato",
        "معلومات الاتصال",
        "الاتصال",
    ),
    "personal": (
        "personal information",
        "personal details",
        "personal data",
        "kişisel bilgiler",
        "persönliche daten",
        "persönliche angaben",
        "informations personnelles",
        "datos personales",
        "dati personali",
        "dados pessoais",
        "المعلومات الشخصية",
    ),
    "custom": (
        "honors-awards",
        "honors & awards",
        "honors and awards",
        "awards",
        "honors",
        "achievements",
        "publications",
        "volunteer experience",
        "volunteering",
        "courses",
        "ödüller",
        "başarılar",
        "yayınlar",
        "gönüllü çalışmalar",
        "kurslar",
        "auszeichnungen",
        "publikationen",
        "ehrenamt",
        "prix",
        "distinctions",
        "bénévolat",
        "premios",
        "publicaciones",
        "voluntariado",
        "premi",
        "pubblicazioni",
        "volontariato",
        "prêmios",
        "publicações",
    ),
}

MONTHS = (
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "jan",
    "feb",
    "mar",
    "apr",
    "jun",
    "jul",
    "aug",
    "sep",
    "sept",
    "oct",
    "nov",
    "dec",
    "ocak",
    "subat",
    "mart",
    "nisan",
    "mayis",
    "haziran",
    "temmuz",
    "agustos",
    "eylul",
    "ekim",
    "kasim",
    "aralik",
    "januar",
    "februar",
    "marz",
    "mai",
    "juni",
    "juli",
    "oktober",
    "okt",
    "dezember",
    "dez",
    "janvier",
    "janv",
    "fevrier",
    "fevr",
    "mars",
    "avril",
    "avr",
    "juin",
    "juillet",
    "juil",
    "aout",
    "septembre",
    "octobre",
    "novembre",
    "decembre",
    "enero",
    "ene",
    "febrero",
    "marzo",
    "abril",
    "mayo",
    "junio",
    "julio",
    "agosto",
    "ago",
    "septiembre",
    "setiembre",
    "octubre",
    "noviembre",
    "diciembre",
    "dic",
    "gennaio",
    "gen",
    "febbraio",
    "aprile",
    "maggio",
    "giugno",
    "luglio",
    "settembre",
    "ottobre",
    "dicembre",
    "janeiro",
    "fevereiro",
    "fev",
    "marco",
    "maio",
    "junho",
    "julho",
    "setembro",
    "set",
    "outubro",
    "out",
    "novembro",
    "dezembro",
)
PRESENT_WORDS = (
    "present",
    "current",
    "currently",
    "now",
    "today",
    "ongoing",
    "halen",
    "hala",
    "gunumuz",
    "devam ediyor",
    "simdi",
    "heute",
    "bis heute",
    "jetzt",
    "aktuell",
    "derzeit",
    "aujourd'hui",
    "actuel",
    "actuellement",
    "en cours",
    "actualidad",
    "presente",
    "actual",
    "actualmente",
    "hoy",
    "oggi",
    "in corso",
    "attuale",
    "atual",
    "atualmente",
    "o momento",
    "momento",
)
