extension StudioFormulaMarkup {
    /// `FORMULA_TEMPLATES` from the desktop formula dialog.
    static let templates: [Group] = [
        Group(id: "basic", labelKey: "viewer.formula.groups.basic", items: [
            #"\frac{a}{b}"#,
            #"x^{n}"#,
            #"x_{i}"#,
            #"\sqrt{x}"#,
            #"\sqrt[n]{x}"#,
            #"\left| x \right|"#,
            #"\pm"#,
            #"\times"#,
            #"÷"#,
            #"\neq"#,
            #"\leq"#,
            #"\geq"#,
            #"\approx"#,
            #"\infty"#,
            #"\%"#,
            #"\cdot"#,
        ]),
        Group(id: "calculus", labelKey: "viewer.formula.groups.calculus", items: [
            #"\int f(x)\,dx"#,
            #"\int_{a}^{b} f(x)\,dx"#,
            #"\iint_{D} f\,dA"#,
            #"\oint_{C} \vec{F}\cdot d\vec{r}"#,
            #"\frac{d}{dx} f(x)"#,
            #"f'(x)"#,
            #"\frac{\partial f}{\partial x}"#,
            #"\lim_{x \to \infty} f(x)"#,
            #"\sum_{i=1}^{n} a_i"#,
            #"\prod_{i=1}^{n} a_i"#,
            #"\nabla f"#,
            #"e^{i\pi} + 1 = 0"#,
        ]),
        Group(id: "algebra", labelKey: "viewer.formula.groups.algebra", items: [
            #"x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}"#,
            #"\binom{n}{k}"#,
            #"\log_{a} x"#,
            #"\ln x"#,
            #"(a + b)^2 = a^2 + 2ab + b^2"#,
            #"a^2 - b^2 = (a - b)(a + b)"#,
            #"a^m \cdot a^n = a^{m+n}"#,
            #"\log_a (xy) = \log_a x + \log_a y"#,
            #"\vec{v}"#,
            #"\lfloor x \rfloor \quad \lceil x \rceil"#,
            #"x \equiv a \pmod{n}"#,
        ]),
        Group(id: "matrices", labelKey: "viewer.formula.groups.matrices", items: [
            #"\begin{pmatrix} a & b \\ c & d \end{pmatrix}"#,
            #"\begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}"#,
            #"\begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc"#,
            #"I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}"#,
            #"A = \begin{bmatrix} a_{11} & \cdots & a_{1n} \\ \vdots & \ddots & \vdots \\ a_{m1} & \cdots & a_{mn} \end{bmatrix}"#,
            #"\left[\begin{array}{cc|c} 1 & 2 & 3 \\ 4 & 5 & 6 \end{array}\right]"#,
            #"\begin{pmatrix} x \\ y \\ z \end{pmatrix}"#,
            #"A^{T} \quad A^{-1} \quad \det(A)"#,
            #"A^{-1} = \frac{1}{ad - bc}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}"#,
            #"\begin{cases} 2x + y = 5 \\ x - y = 1 \end{cases}"#,
            #"\begin{aligned} a_1x + b_1y &= c_1 \\ a_2x + b_2y &= c_2 \end{aligned}"#,
            #"f(x) = \begin{cases} x & x \geq 0 \\ -x & x < 0 \end{cases}"#,
        ]),
        Group(id: "logic", labelKey: "viewer.formula.groups.logic", items: [
            #"\in \quad \notin"#,
            #"A \subset B \quad A \subseteq B"#,
            #"A \cup B \quad A \cap B"#,
            #"A \setminus B \quad A^{c}"#,
            #"\emptyset"#,
            #"\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R} \subset \mathbb{C}"#,
            #"\{ x \in \mathbb{R} \mid x > 0 \}"#,
            #"[a, b) \quad (a, \infty)"#,
            #"s(A \cup B) = s(A) + s(B) - s(A \cap B)"#,
            #"\forall x \; \exists y"#,
            #"p \land q \quad p \lor q \quad \lnot p"#,
            #"p \Rightarrow q \quad p \Leftrightarrow q"#,
            #"f\colon A \to B"#,
            #"(g \circ f)(x)"#,
        ]),
        Group(id: "statistics", labelKey: "viewer.formula.groups.statistics", items: [
            #"\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i"#,
            #"\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n} (x_i - \mu)^2}"#,
            #"s^2 = \frac{1}{n-1}\sum_{i=1}^{n} (x_i - \bar{x})^2"#,
            #"P(A) = \frac{s(A)}{s(E)}"#,
            #"P(A \mid B) = \frac{P(A \cap B)}{P(B)}"#,
            #"P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B)}"#,
            #"P(A \cup B) = P(A) + P(B) - P(A \cap B)"#,
            #"C(n, r) = \frac{n!}{r!\,(n-r)!}"#,
            #"P(n, r) = \frac{n!}{(n-r)!}"#,
            #"P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}"#,
            #"E[X] = \sum_{i} x_i\, p_i"#,
            #"z = \frac{x - \mu}{\sigma}"#,
            #"f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}"#,
        ]),
        Group(id: "layout", labelKey: "viewer.formula.groups.layout", items: [
            #"\begin{aligned} f(x) &= (x+1)^2 \\ &= x^2 + 2x + 1 \end{aligned}"#,
            #"\begin{gathered} a + b = c \\ d - e = f \end{gathered}"#,
            #"a + b = c \tag{1}"#,
            #"\boxed{E = mc^2}"#,
            #"\underbrace{a + \cdots + a}_{n}"#,
            #"\overbrace{x + y}^{k}"#,
            #"\text{…} \quad x^2"#,
            #"\cancel{x}"#,
            #"\enclose{circle}{1}"#,
            #"\color{red}{x}"#,
            #"A \xrightarrow[b]{a} B"#,
            #"\stackrel{?}{=}"#,
        ]),
        Group(id: "geometry", labelKey: "viewer.formula.groups.geometry", items: [
            #"a^2 + b^2 = c^2"#,
            #"A = \pi r^2"#,
            #"C = 2\pi r"#,
            #"V = \frac{4}{3}\pi r^3"#,
            #"\sin^2\theta + \cos^2\theta = 1"#,
            #"\tan\theta = \frac{\sin\theta}{\cos\theta}"#,
            #"\angle ABC = 90^\circ"#,
            #"\triangle ABC \cong \triangle DEF"#,
            #"AB \parallel CD"#,
            #"AB \perp CD"#,
            #"\overline{AB}"#,
            #"\overrightarrow{AB}"#,
        ]),
        Group(id: "greek", labelKey: "viewer.formula.groups.greek", items: [
            #"\alpha"#,
            #"\beta"#,
            #"\gamma"#,
            #"\delta"#,
            #"\varepsilon"#,
            #"\theta"#,
            #"\lambda"#,
            #"\mu"#,
            #"\pi"#,
            #"\rho"#,
            #"\sigma"#,
            #"\tau"#,
            #"\varphi"#,
            #"\omega"#,
            #"\Delta"#,
            #"\Sigma"#,
            #"\Phi"#,
            #"\Omega"#,
        ]),
        Group(id: "physics", labelKey: "viewer.formula.groups.physics", items: [
            #"\vec{F} = m\vec{a}"#,
            #"E = mc^2"#,
            #"E_k = \frac{1}{2}mv^2"#,
            #"E_p = mgh"#,
            #"F = G\frac{m_1 m_2}{r^2}"#,
            #"F = k\frac{q_1 q_2}{r^2}"#,
            #"V = IR"#,
            #"P = VI"#,
            #"v = \frac{\Delta x}{\Delta t}"#,
            #"x = x_0 + v_0 t + \frac{1}{2}at^2"#,
            #"\vec{p} = m\vec{v}"#,
            #"v = \lambda f"#,
            #"E = h\nu"#,
            #"PV = nRT"#,
            #"i\hbar\frac{\partial}{\partial t}\Psi = \hat{H}\Psi"#,
            #"\nabla \cdot \vec{E} = \frac{\rho}{\varepsilon_0}"#,
        ]),
        Group(id: "chemistry", labelKey: "viewer.formula.groups.chemistry", items: [
            #"\ce{H2O}"#,
            #"\ce{2H2 + O2 -> 2H2O}"#,
            #"\ce{CH4 + 2O2 -> CO2 + 2H2O}"#,
            #"\ce{N2 + 3H2 <=> 2NH3}"#,
            #"\ce{SO4^2-}"#,
            #"\ce{NaCl_{(aq)}}"#,
            #"\ce{CaCO3 ->[\Delta] CaO + CO2 ^}"#,
            #"\ce{^{14}_{6}C}"#,
        ]),
    ]

    /// `insertAt`: inserts a template, adding a space after a trailing letter unless it starts a command.
    static func insert(_ insertion: String, into text: String, at range: Range<Int>) -> (text: String, caret: Int) {
        let chars = Array(text)
        let from = max(0, min(range.lowerBound, chars.count)), to = max(from, min(range.upperBound, chars.count))
        let before = String(chars[..<from])
        let spacer = (before.last.map { $0.isASCII && $0.isLetter } ?? false) && !insertion.hasPrefix("\\") ? " " : ""
        let inserted = spacer + insertion
        return (before + inserted + String(chars[to...]), from + inserted.count)
    }
}
